/*
SQLyog Ultimate v12.5.1 (64 bit)
MySQL - 10.4.25-MariaDB 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `products` (
	`id` bigint (20),
	`category_id` int (11),
	`subcategory_id` int (11),
	`brand` varchar (765),
	`product_name` varchar (765),
	`product_code` varchar (765),
	`product_quantity` varchar (765),
	`product_details` text ,
	`product_color` varchar (765),
	`product_size` varchar (765),
	`selling_price` varchar (765),
	`discount_price` varchar (765),
	`video_link` varchar (765),
	`main_slider` int (11),
	`hot_deal` int (11),
	`best_rated` int (11),
	`mid_slider` int (11),
	`hot_new` int (11),
	`buyone_getone` int (11),
	`trend` int (11),
	`image_one` varchar (765),
	`image_two` varchar (765),
	`image_three` varchar (765),
	`status` int (11),
	`created_at` timestamp ,
	`updated_at` timestamp 
); 
insert into `products` (`id`, `category_id`, `subcategory_id`, `brand`, `product_name`, `product_code`, `product_quantity`, `product_details`, `product_color`, `product_size`, `selling_price`, `discount_price`, `video_link`, `main_slider`, `hot_deal`, `best_rated`, `mid_slider`, `hot_new`, `buyone_getone`, `trend`, `image_one`, `image_two`, `image_three`, `status`, `created_at`, `updated_at`) values('1','0',NULL,'0','包丁1','','','','新着','new','10900','9000',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'assets/img/25667370_m.png','assets/img/25667369_m.png',NULL,NULL,NULL,NULL);
insert into `products` (`id`, `category_id`, `subcategory_id`, `brand`, `product_name`, `product_code`, `product_quantity`, `product_details`, `product_color`, `product_size`, `selling_price`, `discount_price`, `video_link`, `main_slider`, `hot_deal`, `best_rated`, `mid_slider`, `hot_new`, `buyone_getone`, `trend`, `image_one`, `image_two`, `image_three`, `status`, `created_at`, `updated_at`) values('2','0',NULL,'0','包丁1','','','','新着',NULL,'10900','9000',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'assets/img/25667370_m.png','assets/img/25667369_m.png',NULL,NULL,NULL,NULL);
insert into `products` (`id`, `category_id`, `subcategory_id`, `brand`, `product_name`, `product_code`, `product_quantity`, `product_details`, `product_color`, `product_size`, `selling_price`, `discount_price`, `video_link`, `main_slider`, `hot_deal`, `best_rated`, `mid_slider`, `hot_new`, `buyone_getone`, `trend`, `image_one`, `image_two`, `image_three`, `status`, `created_at`, `updated_at`) values('3','0',NULL,'0','包丁1','','','','新着',NULL,'10900','9000',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'assets/img/25667370_m.png','assets/img/25667369_m.png',NULL,NULL,NULL,NULL);
insert into `products` (`id`, `category_id`, `subcategory_id`, `brand`, `product_name`, `product_code`, `product_quantity`, `product_details`, `product_color`, `product_size`, `selling_price`, `discount_price`, `video_link`, `main_slider`, `hot_deal`, `best_rated`, `mid_slider`, `hot_new`, `buyone_getone`, `trend`, `image_one`, `image_two`, `image_three`, `status`, `created_at`, `updated_at`) values('4','0',NULL,'0','包丁1','','','','新着',NULL,'10900','9000',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'assets/img/25667370_m.png','assets/img/25667369_m.png',NULL,NULL,NULL,NULL);
insert into `products` (`id`, `category_id`, `subcategory_id`, `brand`, `product_name`, `product_code`, `product_quantity`, `product_details`, `product_color`, `product_size`, `selling_price`, `discount_price`, `video_link`, `main_slider`, `hot_deal`, `best_rated`, `mid_slider`, `hot_new`, `buyone_getone`, `trend`, `image_one`, `image_two`, `image_three`, `status`, `created_at`, `updated_at`) values('5','0',NULL,'0','包丁1','','','','新着','new','10900','9000',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'assets/img/25667370_m.png','assets/img/25667369_m.png',NULL,NULL,NULL,NULL);
insert into `products` (`id`, `category_id`, `subcategory_id`, `brand`, `product_name`, `product_code`, `product_quantity`, `product_details`, `product_color`, `product_size`, `selling_price`, `discount_price`, `video_link`, `main_slider`, `hot_deal`, `best_rated`, `mid_slider`, `hot_new`, `buyone_getone`, `trend`, `image_one`, `image_two`, `image_three`, `status`, `created_at`, `updated_at`) values('6','0',NULL,'0','包丁1','','','','出刃',NULL,'10900','9000',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'assets/img/25667370_m.png','assets/img/25667369_m.png',NULL,NULL,NULL,NULL);
insert into `products` (`id`, `category_id`, `subcategory_id`, `brand`, `product_name`, `product_code`, `product_quantity`, `product_details`, `product_color`, `product_size`, `selling_price`, `discount_price`, `video_link`, `main_slider`, `hot_deal`, `best_rated`, `mid_slider`, `hot_new`, `buyone_getone`, `trend`, `image_one`, `image_two`, `image_three`, `status`, `created_at`, `updated_at`) values('7','0',NULL,'0','包丁1','','','','出刃',NULL,'10900','9000',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'assets/img/25667370_m.png','assets/img/25667369_m.png',NULL,NULL,NULL,NULL);
insert into `products` (`id`, `category_id`, `subcategory_id`, `brand`, `product_name`, `product_code`, `product_quantity`, `product_details`, `product_color`, `product_size`, `selling_price`, `discount_price`, `video_link`, `main_slider`, `hot_deal`, `best_rated`, `mid_slider`, `hot_new`, `buyone_getone`, `trend`, `image_one`, `image_two`, `image_three`, `status`, `created_at`, `updated_at`) values('8','0',NULL,'0','包丁1','','','','出刃',NULL,'10900','9000',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'assets/img/25667370_m.png','assets/img/25667369_m.png',NULL,NULL,NULL,NULL);
insert into `products` (`id`, `category_id`, `subcategory_id`, `brand`, `product_name`, `product_code`, `product_quantity`, `product_details`, `product_color`, `product_size`, `selling_price`, `discount_price`, `video_link`, `main_slider`, `hot_deal`, `best_rated`, `mid_slider`, `hot_new`, `buyone_getone`, `trend`, `image_one`, `image_two`, `image_three`, `status`, `created_at`, `updated_at`) values('9','0',NULL,'0','包丁1','','','','出刃','new','10900','9000',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'assets/img/25667370_m.png','assets/img/25667369_m.png',NULL,NULL,NULL,NULL);
insert into `products` (`id`, `category_id`, `subcategory_id`, `brand`, `product_name`, `product_code`, `product_quantity`, `product_details`, `product_color`, `product_size`, `selling_price`, `discount_price`, `video_link`, `main_slider`, `hot_deal`, `best_rated`, `mid_slider`, `hot_new`, `buyone_getone`, `trend`, `image_one`, `image_two`, `image_three`, `status`, `created_at`, `updated_at`) values('10','0',NULL,'0','包丁1','','','','出刃',NULL,'10900','9000',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'assets/img/25667370_m.png','assets/img/25667369_m.png',NULL,NULL,NULL,NULL);
insert into `products` (`id`, `category_id`, `subcategory_id`, `brand`, `product_name`, `product_code`, `product_quantity`, `product_details`, `product_color`, `product_size`, `selling_price`, `discount_price`, `video_link`, `main_slider`, `hot_deal`, `best_rated`, `mid_slider`, `hot_new`, `buyone_getone`, `trend`, `image_one`, `image_two`, `image_three`, `status`, `created_at`, `updated_at`) values('11','0',NULL,'0','包丁1','','','','牛刀',NULL,'10900','9000',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'assets/img/25667370_m.png','assets/img/25667369_m.png',NULL,NULL,NULL,NULL);
insert into `products` (`id`, `category_id`, `subcategory_id`, `brand`, `product_name`, `product_code`, `product_quantity`, `product_details`, `product_color`, `product_size`, `selling_price`, `discount_price`, `video_link`, `main_slider`, `hot_deal`, `best_rated`, `mid_slider`, `hot_new`, `buyone_getone`, `trend`, `image_one`, `image_two`, `image_three`, `status`, `created_at`, `updated_at`) values('12','0',NULL,'0','包丁1','','','','牛刀','new','10900','9000',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'assets/img/25667370_m.png','assets/img/25667369_m.png',NULL,NULL,NULL,NULL);
insert into `products` (`id`, `category_id`, `subcategory_id`, `brand`, `product_name`, `product_code`, `product_quantity`, `product_details`, `product_color`, `product_size`, `selling_price`, `discount_price`, `video_link`, `main_slider`, `hot_deal`, `best_rated`, `mid_slider`, `hot_new`, `buyone_getone`, `trend`, `image_one`, `image_two`, `image_three`, `status`, `created_at`, `updated_at`) values('13','0',NULL,'0','包丁1','','','','牛刀',NULL,'10900','9000',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'assets/img/25667370_m.png','assets/img/25667369_m.png',NULL,NULL,NULL,NULL);
insert into `products` (`id`, `category_id`, `subcategory_id`, `brand`, `product_name`, `product_code`, `product_quantity`, `product_details`, `product_color`, `product_size`, `selling_price`, `discount_price`, `video_link`, `main_slider`, `hot_deal`, `best_rated`, `mid_slider`, `hot_new`, `buyone_getone`, `trend`, `image_one`, `image_two`, `image_three`, `status`, `created_at`, `updated_at`) values('14','0',NULL,'0','包丁1','','','','牛刀','new','10900','9000',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'assets/img/25667370_m.png','assets/img/25667369_m.png',NULL,NULL,NULL,NULL);
insert into `products` (`id`, `category_id`, `subcategory_id`, `brand`, `product_name`, `product_code`, `product_quantity`, `product_details`, `product_color`, `product_size`, `selling_price`, `discount_price`, `video_link`, `main_slider`, `hot_deal`, `best_rated`, `mid_slider`, `hot_new`, `buyone_getone`, `trend`, `image_one`, `image_two`, `image_three`, `status`, `created_at`, `updated_at`) values('15','0',NULL,'0','包丁1','','','','牛刀',NULL,'10900','9000',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'assets/img/25667370_m.png','assets/img/25667369_m.png',NULL,NULL,NULL,NULL);
insert into `products` (`id`, `category_id`, `subcategory_id`, `brand`, `product_name`, `product_code`, `product_quantity`, `product_details`, `product_color`, `product_size`, `selling_price`, `discount_price`, `video_link`, `main_slider`, `hot_deal`, `best_rated`, `mid_slider`, `hot_new`, `buyone_getone`, `trend`, `image_one`, `image_two`, `image_three`, `status`, `created_at`, `updated_at`) values('16','0',NULL,'0','包丁1','','','','ペティ','new','10900','9000',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'assets/img/25667370_m.png','assets/img/25667369_m.png',NULL,NULL,NULL,NULL);
insert into `products` (`id`, `category_id`, `subcategory_id`, `brand`, `product_name`, `product_code`, `product_quantity`, `product_details`, `product_color`, `product_size`, `selling_price`, `discount_price`, `video_link`, `main_slider`, `hot_deal`, `best_rated`, `mid_slider`, `hot_new`, `buyone_getone`, `trend`, `image_one`, `image_two`, `image_three`, `status`, `created_at`, `updated_at`) values('17','0',NULL,'0','包丁1','','','','ペティ',NULL,'10900','9000',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'assets/img/25667370_m.png','assets/img/25667369_m.png',NULL,NULL,NULL,NULL);
insert into `products` (`id`, `category_id`, `subcategory_id`, `brand`, `product_name`, `product_code`, `product_quantity`, `product_details`, `product_color`, `product_size`, `selling_price`, `discount_price`, `video_link`, `main_slider`, `hot_deal`, `best_rated`, `mid_slider`, `hot_new`, `buyone_getone`, `trend`, `image_one`, `image_two`, `image_three`, `status`, `created_at`, `updated_at`) values('18','0',NULL,'0','包丁1','','','','ペティ',NULL,'10900','9000',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'assets/img/25667370_m.png','assets/img/25667369_m.png',NULL,NULL,NULL,NULL);
insert into `products` (`id`, `category_id`, `subcategory_id`, `brand`, `product_name`, `product_code`, `product_quantity`, `product_details`, `product_color`, `product_size`, `selling_price`, `discount_price`, `video_link`, `main_slider`, `hot_deal`, `best_rated`, `mid_slider`, `hot_new`, `buyone_getone`, `trend`, `image_one`, `image_two`, `image_three`, `status`, `created_at`, `updated_at`) values('19','0',NULL,'0','包丁1','','','','ペティ','new','10900','9000',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'assets/img/25667370_m.png','assets/img/25667369_m.png',NULL,NULL,NULL,NULL);
insert into `products` (`id`, `category_id`, `subcategory_id`, `brand`, `product_name`, `product_code`, `product_quantity`, `product_details`, `product_color`, `product_size`, `selling_price`, `discount_price`, `video_link`, `main_slider`, `hot_deal`, `best_rated`, `mid_slider`, `hot_new`, `buyone_getone`, `trend`, `image_one`, `image_two`, `image_three`, `status`, `created_at`, `updated_at`) values('20','0',NULL,'0','包丁1','','','','ペティ',NULL,'10900','9000',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'assets/img/25667370_m.png','assets/img/25667369_m.png',NULL,NULL,NULL,NULL);
